services:
  postgres:
    image: postgres:17.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Asia/Tokyo'
    volumes:
      - db_vol:/var/lib/postgresql/data
  redis:
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_vol:/data:delegated
volumes:
  db_vol:
  redis_vol:

