services:
  postgres:
    image: postgres:17.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Asia/Tokyo'
    volumes:
      - db_vol:/var/lib/postgresql/data
volumes:
  db_vol:

